server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: Mysqldb@1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect